name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}

    - name: Deploy over SSH
      run: |
        ssh -o StrictHostKeyChecking=no deployuser@206.189.47.162 "
          set -x
          cd /opt/app &&
          git checkout master &&
          git pull origin master &&
          cd docker-compose-file &&
          docker-compose down
          docker-compose --env-file ../credentials-docker.env build --progress=plain &&
          docker-compose --env-file ../credentials-docker.env up -d
        "